name: pia_service

services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env.development
    volumes:
      # DB data
      - pia_postgres_data:/var/lib/postgresql/data
      # SQL Migrate script is executed when the container's data volume is first initialized
      - ./drizzle/migrate.sql:/docker-entrypoint-initdb.d/migrate.sql:ro

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env.development
    volumes:
      - pia_minio_data:/data

  fake-smtp:
    image: gessnerfl/fake-smtp-server:latest
    container_name: fake-smtp
    restart: unless-stopped
    ports:
      - "8025:8025" # SMTP
      - "8080:8080" # web GUI
      - "8081:8081"
    env_file:
      - .env.development

  astro-http-server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: astro_http_server
    restart: unless-stopped
    ports:
      - "80:4321"
    env_file:
      - .env.development
    depends_on:
      - postgres
      - minio
      - fake-smtp

volumes:
  pia_postgres_data:
  pia_minio_data:
